apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
  namespace: pokemons
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  