apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-efs-pv
  namespace: pokemons
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01d45f139a617fa86